name: Build source code


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:  "main"
    paths-ignore:
      - 'test/**'
    path:
      - 'src/**'
      - 'inc/**'
      - '*.c'
      - '*.h'
      - 'CMake**'
      - '*.cmake'
  pull_request:
    branches: "main"
    paths-ignore:
      - 'test/**'
    path:
      - 'src/**'
      - 'inc/**'
      - '*.c'
      - '*.h'
      - 'CMake**'
      - '*.cmake'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build 
          cd build
          cmake ..
          make